baseURL = 'https://brianjcohen.github.io/'
languageCode = 'en-us'
title = 'Thinking and Fixing'
theme = 'beautifulhugo'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[Params]
homeTitle = "Thinking and Fixing"
description = "Thoughts on Linux, desktop computing, and the things I've learned fixing them"
subtitle = "I'm a Software Engineer in the State of New York, USA. Posts are mostly about Linux on the desktop but, hey, you never know."
logo = "images/cover.jpg"
mainSections = ["posts"]
readingTime = true
wordCount = true
socialShare = true
showRelatedPosts = true

[Params.author]
name = "Brian Cohen"
linkedin = "brian-j-cohen"
github = "brianjcohen"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[markup]
[markup.highlight]
style = 'monokai'
